<?xml version = "1.0"?>
<package format = "3">
    <name>submarine_bringup</name>
    <version>0.0.1</version>
    <description>Bringup launch file for submarine simulation</description>

    <maintainer email = "yeochi1201@gmail.com">yeochi1201</maintainer>
    <license>Apache-2.0</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <!--launch system-->
    <exec_depend>launch</exec_depend>
    <exec_depend>launch_ros</exec_depend>

    <!--gazebo fortress, ros-->
    <exec_depend>ros_gz_sim</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>